alias: Item voor item
description: ""
triggers: []
conditions: []
actions:
  - action: todo.get_items
    metadata: {}
    data:
      status: needs_action
    target:
      entity_id: todo.mealie_boodschappenlijst
    response_variable: mylist
  - repeat:
      for_each: "{{ mylist['todo.mealie_boodschappenlijst']['items'] }}"
      sequence:
        - data:
            title: Ieder item
            message: "{{ repeat.item.summary }}"
          action: notify.mobile_app_fvh_xs_max
mode: single
